// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-9ihzllbrj315Fh10UPvHXa8eltJtf0',
    appId: '1:805160954319:web:3d8acd9be9ccd24448caba',
    messagingSenderId: '805160954319',
    projectId: 'save-data-user-af081',
    authDomain: 'save-data-user-af081.firebaseapp.com',
    storageBucket: 'save-data-user-af081.firebasestorage.app',
    measurementId: 'G-RNQX3RVCL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn2XYs3WyX6MXJs4WuV6ZiI9E2yONKNAc',
    appId: '1:805160954319:android:0db33d3d9975387748caba',
    messagingSenderId: '805160954319',
    projectId: 'save-data-user-af081',
    storageBucket: 'save-data-user-af081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTXo_lDewkcP4CJzBrIb-b755Yf5A92C4',
    appId: '1:805160954319:ios:d1ea817359ada0e048caba',
    messagingSenderId: '805160954319',
    projectId: 'save-data-user-af081',
    storageBucket: 'save-data-user-af081.firebasestorage.app',
    iosBundleId: 'com.example.userData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTXo_lDewkcP4CJzBrIb-b755Yf5A92C4',
    appId: '1:805160954319:ios:d1ea817359ada0e048caba',
    messagingSenderId: '805160954319',
    projectId: 'save-data-user-af081',
    storageBucket: 'save-data-user-af081.firebasestorage.app',
    iosBundleId: 'com.example.userData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs-9ihzllbrj315Fh10UPvHXa8eltJtf0',
    appId: '1:805160954319:web:b06d647d64c4b03448caba',
    messagingSenderId: '805160954319',
    projectId: 'save-data-user-af081',
    authDomain: 'save-data-user-af081.firebaseapp.com',
    storageBucket: 'save-data-user-af081.firebasestorage.app',
    measurementId: 'G-NFPHFZ0WNC',
  );
}
